### ISSUE TITLE
Unable to start wekan

### ISSUE THREAD

**Issue by extraymond** [kubiko/wekan-snap#1]
● snap.wekan-ondra.mongodb.service - Service for snap application wekan-ondra.mongodb
   Loaded: loaded (/etc/systemd/system/snap.wekan-ondra.mongodb.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since 五 2016-11-04 02:14:56 CST; 11min ago
 Main PID: 12126 (code=exited, status=100)

11月 04 02:14:56 ubuntu-home systemd[1]: snap.wekan-ondra.mongodb.service: Unit entered failed state.
11月 04 02:14:56 ubuntu-home systemd[1]: snap.wekan-ondra.mongodb.service: Failed with result 'exit-code'.
11月 04 02:14:56 ubuntu-home systemd[1]: snap.wekan-ondra.mongodb.service: Service hold-off time over, scheduling restart.
11月 04 02:14:56 ubuntu-home systemd[1]: Stopped Service for snap application wekan-ondra.mongodb.
11月 04 02:14:56 ubuntu-home systemd[1]: snap.wekan-ondra.mongodb.service: Start request repeated too quickly.
11月 04 02:14:56 ubuntu-home systemd[1]: Failed to start Service for snap application wekan-ondra.mongodb.
11月 04 02:14:56 ubuntu-home systemd[1]: snap.wekan-ondra.mongodb.service: Unit entered failed state.
11月 04 02:14:56 ubuntu-home systemd[1]: snap.wekan-ondra.mongodb.service: Failed with result 'start-limit-hit'.

This is the error indicating monogodb can't start properly.

**Comment by kubiko** [comment]
can you share more about environment you are running it at?

**Comment by extraymond** [comment]
I'm on ubuntu 16.10! Install wekan using:
sudo snap install wekan-ondra

**Comment by extraymond** [comment]
Is there anyway I can find the source: parts/wekan/install/programs/server/
I was trying to create the snap package on my own

**Comment by kubiko** [comment]
hmm, just installed Ubuntu 16.10 and working just fine for me
Which channel are you running?
edge and beta have wekan 0.11.0_rc2, stable has 0.10.1
you can create snap yourself, just clone this git repo and run $ snapcraft
it will build it for you.
wekan is coming from official wekan bundle, depends on version either
https://github.com/wekan/wekan/releases/download/v0.10.1/wekan-0.10.1.tar.gz
or
https://github.com/wekan/wekan/releases/download/v0.11.0-rc2/wekan-0.11.0-rc2.tar.gz
just go to wekan git repo and you should be able to find there all you need

**Comment by extraymond** [comment]
Thx for the reply! I'll try to test and see if I can get this right, Thx.

**Comment by extraymond** [comment]
Hi! I find the problem!
After installing, I need to manually snap connect wekan-ondra:network and network-bind.
Then do a snap disable and enable to make things work!

A minor problem is that with edge channel, it will go to a blank page where with stable channel I can see the register page.
