### ISSUE TITLE
Database empty / changed after recent update

### ISSUE THREAD

**Issue by anlx-sl** [kubiko/wekan-snap#4]
All data is gone after recent update. Seems a new DB was created and is now being used:
127.0.0.1:27017/admin

Before it was
127.0.0.1:27017/wekan

Is it recommended to move data from db wekan to db admin or will the database name be changed back?

**Comment by kubiko** [comment]
oh dear, what a stupid mistake. Sorry for that and thanks for pointing it out
just kicking off new build, new revision should be up within hour when it bubbles up through the system
you can force refresh on your system once new revision is up
$ snap refresh wekan-ondra

**Comment by anlx-sl** [comment]
OK, thanks  a lot for the information!

**Comment by kubiko** [comment]
OK this is now uploaded to stable channel, so  you should be able to refresh, please let me know if it fixed the problem

**Comment by anlx-sl** [comment]
Yes, it worked! Thank you!

**Comment by kubiko** [comment]
great! And sorry for the inconvenience
Dunno if you know this functionality, but if there is problem with recent revision, before it's fixed you can quickly revert to previous revision by calling:
$ snap revert wekan-ondra
